# Generated by Django 6.0.4 on 2026-05-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userprofile_created_at_userprofile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
