# Generated by Django 6.0.4 on 2026-05-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="photo",
            field=models.ImageField(blank=True, upload_to="photos"),
        ),
    ]
