# Generated by Django 6.0.4 on 2026-05-06 17:33

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0002_pizza_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to=core.services.file_service.upload_pizza_photo
            ),
        ),
    ]
